In [1]:
import numpy as np

In [20]:
x = np.array([3, -2, 5, -1, 2, 6, 0.5, -100])
x

array([   3. ,   -2. ,    5. ,   -1. ,    2. ,    6. ,    0.5, -100. ])

In [21]:
#unsur pertama x
x[0]

np.float64(3.0)

In [22]:
#unsur kedua x
x[1]

np.float64(-2.0)

In [23]:
#unsur pertama dari belakang
x[-1]

np.float64(-100.0)

In [24]:
#unsur ke 6 (5+1) hingga terakhir
x[5:]

array([   6. ,    0.5, -100. ])

In [25]:
#5 unsur pertama
x[:5]

array([ 3., -2.,  5., -1.,  2.])

In [26]:
x

array([   3. ,   -2. ,    5. ,   -1. ,    2. ,    6. ,    0.5, -100. ])

In [29]:
#index 1 hingga 4 (5-1)
x[1:5]

array([-2.,  5., -1.,  2.])