In [122]:
#import numpy dengan alias np
import numpy as np

In [123]:
#buat numpy array
x = np.array([1, -2, 3.0])
x

array([ 1., -2.,  3.])

Operasi Numpy Array

In [124]:
#operasi numpy array
x = np.array([1, 2, -1])
y = np.array([2, 1, 1])

In [91]:
#penjumlahan
x + y

array([3, 3, 0])

In [125]:
#pengurangan
x - y

array([-1,  1, -2])

In [126]:
#perkalian titik
x * y

array([ 2,  2, -1])

In [127]:
#pembagian titik
x / y

array([ 0.5,  2. , -1. ])

In [128]:
#kali skalar
2 * x

array([ 2,  4, -2])

### Generate Array (membangun array)

In [129]:
#array nol 
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [130]:
#array satu
x = np.ones(7)
x

array([1., 1., 1., 1., 1., 1., 1.])

In [131]:
#array random antara 0 dan 1
x = np.random.random(5)
x

array([0.46948465, 0.14258369, 0.04065439, 0.33766739, 0.12685466])

In [133]:
#array random bilangan bulat antara -5 dan 5 (-5 <= x < 5) -> termasuk -5 tetapi tidak termasuk 5
np.random.randint(-5, 5, 10)

array([-4,  4, -5,  0,  4,  1,  2,  3,  4, -1], dtype=int32)

In [134]:
#array konstan
x = np.full(5, 8) #ukuran 5 dengan entri 8
x

array([8, 8, 8, 8, 8])

In [143]:
#array dengan suatu permulaan
x = np.arange(1,10,2) #array dimulai dari 1 hingga < 10 dengan penambahan (langkah) 2
x

array([1, 3, 5, 7, 9])

In [144]:
x = np.arange(10,1,-2) #array dimulai dari 10 dengan langkah -2 hingga > 1
x

array([10,  8,  6,  4,  2])

In [137]:
np.arange(10) #otomatis dari 0 hingga < 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.arange(1,6) #mulai dari 1 hingga <6

array([1, 2, 3, 4, 5])

In [139]:
np.arange(0, 5, 0.5) #mulai dari 0, meningkat 0.5 hingga < 5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [140]:
#array mulai dari 0 hingga 2 (termasuk 2) sebanyak 10 titik
x = np.linspace(0, 2, 10)
x

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [141]:
#jika tidak didefinisikan banyak titiknya maka otomatis mengembalikan (default) sebanyak 50 titik
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [145]:
#partisi/selang antara a hingga b (a < b) terbagi dalam banyak 5 partisi/selang
a = 0
b = 1
partisi = 5
np.linspace(a, b, partisi+1)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

### Fungsi Matematika

In [180]:
x = np.random.randint(-10,10, 5)
x

array([ 1,  9, -2,  6,  5], dtype=int32)

In [181]:
#nilai mutlak (absolute)
np.absolute(x)

array([1, 9, 2, 6, 5], dtype=int32)

In [196]:
#akar kuadrat
z = np.array([0.4, 1, 9, 15])
np.sqrt(z)

array([0.63245553, 1.        , 3.        , 3.87298335])

In [197]:
#sinus
np.sin(x)

array([-0.84147098,  0.95892427,  0.84147098, -0.84147098, -0.14112001,
       -0.90929743,  0.95892427,  0.14112001, -0.84147098, -0.7568025 ])

In [198]:
#cosinus
np.cos(x)

array([ 0.54030231,  0.28366219,  0.54030231,  0.54030231, -0.9899925 ,
       -0.41614684,  0.28366219, -0.9899925 ,  0.54030231, -0.65364362])

In [199]:
#tangent
np.tan(x)

array([-1.55740772,  3.38051501,  1.55740772, -1.55740772,  0.14254654,
        2.18503986,  3.38051501, -0.14254654, -1.55740772,  1.15782128])

In [200]:
#exponent e^x
np.exp(x)

array([3.67879441e-01, 6.73794700e-03, 2.71828183e+00, 3.67879441e-01,
       4.97870684e-02, 1.35335283e-01, 6.73794700e-03, 2.00855369e+01,
       3.67879441e-01, 5.45981500e+01])

In [201]:
#logaritma natural (ln)
y = np.array([1, 10, 3])
np.log(y)

array([0.        , 2.30258509, 1.09861229])

In [202]:
#logaritma basis 10 
y = np.array([1, 10, 3])
np.log10(y)

array([0.        , 1.        , 0.47712125])

### Statistik

In [191]:
x = np.random.randint(-5, 5, 10)
x

array([-1, -5,  1, -1, -3, -2, -5,  3, -1,  4], dtype=int32)

In [192]:
#maksimum
np.max(x)

np.int32(4)

In [193]:
#minimum
np.min(x)

np.int32(-5)

In [203]:
#median
np.median(x)


np.float64(-1.0)

In [208]:
#mean
np.mean(x)

np.float64(-1.0)

In [209]:
#standar deviasi
np.std(x)

np.float64(2.8635642126552705)