In [144]:
import numpy as np
#matrix 3x3
A = np.array([[1, 3, 1], [1, -2, 0], [1, 1, -1]])
A

array([[ 1,  3,  1],
       [ 1, -2,  0],
       [ 1,  1, -1]])

In [146]:
#matrix 2x2
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

Operasi Matriks (Array 2D)

In [147]:
A = np.array([[1,1,0], [-1,2,1], [0,0,1]])
A


array([[ 1,  1,  0],
       [-1,  2,  1],
       [ 0,  0,  1]])

In [148]:
B = np.array([[1,1,1], [-1,-1,-1], [0,0,0]])
B

array([[ 1,  1,  1],
       [-1, -1, -1],
       [ 0,  0,  0]])

In [63]:
A + B

array([[ 2,  2,  1],
       [-2,  1,  0],
       [ 0,  0,  1]])

In [64]:
A - B

array([[ 0,  0, -1],
       [ 0,  3,  2],
       [ 0,  0,  1]])

In [65]:
#kali titik
A * B
#np.multiply(A,B)

array([[ 1,  1,  0],
       [ 1, -2, -1],
       [ 0,  0,  0]])

In [66]:
#kali biasa
A @ B
#np.matmul(A, B)

array([[ 0,  0,  0],
       [-3, -3, -3],
       [ 0,  0,  0]])

In [67]:
#perpangkatan matriks A^2 = AA
A^2

array([[ 3,  3,  2],
       [-3,  0,  3],
       [ 2,  2,  3]])

Generate Matrix (membangun matriks)

In [ ]:
#matriks nol ukuran 3x4
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
#matriks 1 ukuran 2x5
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
#matriks konstan ukuran 2x5 dengan entri 7
np.full((2,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [58]:
#matriks identitas
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
#matriks random antara 0 dan 1 orde 3x3
np.random.random((3,3))

array([[0.2702509 , 0.32837171, 0.26010842],
       [0.41084976, 0.09230568, 0.13851406],
       [0.01519238, 0.68342547, 0.23348847]])

Index & Slicing

In [152]:
A = np.array([[1, 3, 1], [1, -2, 0], [1, 1, -1]])
A

array([[ 1,  3,  1],
       [ 1, -2,  0],
       [ 1,  1, -1]])

In [153]:
A[0,1]

np.int64(3)

In [154]:
A[0][1]

np.int64(3)

In [155]:
#baris 2 (2-1)
A[1,:] 
#A[1][:] 

array([ 1, -2,  0])

In [156]:
#kolom 3 (3-1)
A[:,2]

array([ 1,  0, -1])

In [157]:
#kolom index 2 sampai dengan 3
A[:,1:3]


array([[ 3,  1],
       [-2,  0],
       [ 1, -1]])

In [158]:
#baris index 1 sampai 2
A[1:3,:]

array([[ 1, -2,  0],
       [ 1,  1, -1]])

In [159]:
#baris hingga index 2 dan kolom hingga index 2
A[:2,:2]

array([[ 1,  3],
       [ 1, -2]])

Aljabar Linear

In [160]:
A = np.array([[1, 3, 1], [1, -2, 0], [1, 1, -1]])
A

array([[ 1,  3,  1],
       [ 1, -2,  0],
       [ 1,  1, -1]])

In [161]:
#determinan
np.linalg.det(A)

np.float64(7.999999999999998)

In [162]:
#invers
np.linalg.inv(A)

array([[ 0.25 ,  0.5  ,  0.25 ],
       [ 0.125, -0.25 ,  0.125],
       [ 0.375,  0.25 , -0.625]])

In [163]:
#transpose
np.linalg.matrix_transpose(A)

array([[ 1,  1,  1],
       [ 3, -2,  1],
       [ 1,  0, -1]])

In [164]:
#nilai eigen dan vektor eigen
np.linalg.eig(A)

EigResult(eigenvalues=array([ 2.12488542, -2.76155718, -1.36332824]), eigenvectors=array([[-0.90652757, -0.60238553, -0.13668228],
       [-0.21977036,  0.79099186, -0.2146825 ],
       [-0.36042856, -0.10706796,  0.96707258]]))

In [165]:
#pisahkan nilai eigen (E) dan vektor eigen (V)
E, V = np.linalg.eig(A)

In [166]:
E

array([ 2.12488542, -2.76155718, -1.36332824])

In [167]:
V

array([[-0.90652757, -0.60238553, -0.13668228],
       [-0.21977036,  0.79099186, -0.2146825 ],
       [-0.36042856, -0.10706796,  0.96707258]])

In [170]:
#hanya nilai eigen
np.linalg.eigvals(A)

array([ 2.12488542, -2.76155718, -1.36332824])

In [171]:
#solusi persamaan linear dalam matriks. Solusi dari Ax = u atau x = inv(A) * u
u = np.array([1, 2, 3])
np.linalg.solve(A,u)

array([ 2., -0., -1.])

In [132]:
np.linalg.inv(A) @ u

array([ 2.,  0., -1.])