In [1]:
import numpy as np
#matrix 3x3
A = np.array([[1, 3, 1], [1, -2, 0], [1, 1, -1]])
A

array([[ 1,  3,  1],
       [ 1, -2,  0],
       [ 1,  1, -1]])

In [173]:
#matrix 2x2
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

Operasi Matriks (Array 2D)

In [174]:
A = np.array([[1,1,0], [-1,2,1], [0,0,1]])
A


array([[ 1,  1,  0],
       [-1,  2,  1],
       [ 0,  0,  1]])

In [175]:
B = np.array([[1,1,1], [-1,-1,-1], [0,0,0]])
B

array([[ 1,  1,  1],
       [-1, -1, -1],
       [ 0,  0,  0]])

In [176]:
A + B

array([[ 2,  2,  1],
       [-2,  1,  0],
       [ 0,  0,  1]])

In [177]:
A - B

array([[ 0,  0, -1],
       [ 0,  3,  2],
       [ 0,  0,  1]])

In [178]:
#kali titik
A * B
#np.multiply(A,B)

array([[ 1,  1,  0],
       [ 1, -2, -1],
       [ 0,  0,  0]])

In [179]:
#kali biasa
A @ B
#np.matmul(A, B)

array([[ 0,  0,  0],
       [-3, -3, -3],
       [ 0,  0,  0]])

In [205]:
#perpangkatan matriks A^2 = AA
A**2

array([[1, 9, 1],
       [1, 4, 0],
       [1, 1, 1]])

Generate Matrix (membangun matriks)

In [181]:
#matriks nol ukuran 3x4
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [182]:
#matriks 1 ukuran 2x5
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [183]:
#matriks konstan ukuran 2x5 dengan entri 7
np.full((2,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [184]:
#matriks identitas
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [185]:
#matriks random antara 0 dan 1 orde 3x3
np.random.random((3,3))

array([[0.15463253, 0.27177081, 0.93742699],
       [0.9744383 , 0.24541488, 0.41392755],
       [0.32744236, 0.48364298, 0.75237295]])

Index & Slicing

In [186]:
A = np.array([[1, 3, 1], [1, -2, 0], [1, 1, -1]])
A

array([[ 1,  3,  1],
       [ 1, -2,  0],
       [ 1,  1, -1]])

In [187]:
A[0,1]

np.int64(3)

In [188]:
A[0][1]

np.int64(3)

In [189]:
#baris 2 (2-1)
A[1,:] 
#A[1][:] 

array([ 1, -2,  0])

In [190]:
#kolom 3 (3-1)
A[:,2]

array([ 1,  0, -1])

In [3]:
#kolom index 1 sampai dengan 2
A[:,1:3]


array([[ 3,  1],
       [-2,  0],
       [ 1, -1]])

In [192]:
#baris index 1 sampai 2
A[1:3,:]

array([[ 1, -2,  0],
       [ 1,  1, -1]])

In [193]:
#baris hingga index 2 dan kolom hingga index 2
A[:2,:2]

array([[ 1,  3],
       [ 1, -2]])

Aljabar Linear

In [4]:
A = np.array([[1, 3, 1], [1, -2, 0], [1, 1, -1]])
A

array([[ 1,  3,  1],
       [ 1, -2,  0],
       [ 1,  1, -1]])

In [ ]:
#determinan
np.linalg.det(A)

np.float64(7.999999999999998)

In [196]:
#invers
np.linalg.inv(A)

array([[ 0.25 ,  0.5  ,  0.25 ],
       [ 0.125, -0.25 ,  0.125],
       [ 0.375,  0.25 , -0.625]])

In [197]:
#transpose
np.linalg.matrix_transpose(A)

array([[ 1,  1,  1],
       [ 3, -2,  1],
       [ 1,  0, -1]])

In [198]:
#nilai eigen dan vektor eigen
np.linalg.eig(A)

EigResult(eigenvalues=array([ 2.12488542, -2.76155718, -1.36332824]), eigenvectors=array([[-0.90652757, -0.60238553, -0.13668228],
       [-0.21977036,  0.79099186, -0.2146825 ],
       [-0.36042856, -0.10706796,  0.96707258]]))

In [199]:
#pisahkan nilai eigen (E) dan vektor eigen (V)
E, V = np.linalg.eig(A)

In [200]:
E

array([ 2.12488542, -2.76155718, -1.36332824])

In [201]:
V

array([[-0.90652757, -0.60238553, -0.13668228],
       [-0.21977036,  0.79099186, -0.2146825 ],
       [-0.36042856, -0.10706796,  0.96707258]])

In [202]:
#hanya nilai eigen
np.linalg.eigvals(A)

array([ 2.12488542, -2.76155718, -1.36332824])

In [203]:
#solusi persamaan linear dalam matriks. Solusi dari Ax = u atau x = inv(A) * u
u = np.array([1, 2, 3])
np.linalg.solve(A,u)

array([ 2., -0., -1.])

In [204]:
np.linalg.inv(A) @ u

array([ 2.,  0., -1.])