In [3]:
from scipy import constants

In [8]:
#konstanta
pi = constants.pi
pi

3.141592653589793

In [9]:
bilanganAvogrado = constants.Avogadro
bilanganAvogrado

6.02214076e+23

In [10]:
from scipy.integrate import quad

def integrand(x, a, b):
    return a*x**2 + b

a = 2
b = 1
I = quad(integrand, 0, 1, args=(a,b))
I

(1.6666666666666667, 1.8503717077085944e-14)

In [12]:
from scipy import * #import semua
import numpy as np


In [13]:
A = np.array([[1,0], [3,1]])
A

array([[1, 0],
       [3, 1]])

In [15]:
linalg.det(A)

np.float64(1.0)

In [16]:
linalg.inv(A)

array([[ 1.,  0.],
       [-3.,  1.]])

In [17]:
linalg.eig(A)

(array([1.+0.j, 1.+0.j]),
 array([[ 0.00000000e+00,  7.40148683e-17],
        [ 1.00000000e+00, -1.00000000e+00]]))